site_name: "XiaMoHuaHuo_CN's Docs"
theme:
  language: zh
  name: material
  highlightjs: true
  palette:
    primary: white
    accent: deep purple
  favicon: https://huahuo-cn.tk/images/favicon.png
  logo: https://huahuo-cn.tk/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.share
    - search.suggest
plugins:
  - search
copyright: Copyright &copy; 2023 XiaMoHuaHuo_CN.
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences